"""Generate paydaysuper/data/business_days.json: the national non-business-day table.

DEV-TIME TOOL ONLY. The runtime never imports python-holidays: compliance
output must not change because a transitive dependency updated, and the raw
package output is wrong for SGAA s 6(1) anyway (it lists Brisbane-area
Royal Queensland Show as a QLD PUBLIC holiday).

Method (SGAA 1992 s 6(1) "business day"):
  a day is NOT a business day if it is Sat/Sun, or a public holiday for the
  WHOLE of any State, the ACT or the NT. So: union of PUBLIC-category
  holidays across the 8 listed jurisdictions, minus entries that are not
  whole-of-jurisdiction, weekends excluded (computed at runtime).

Usage:
    uv run --locked --extra dev --python 3.12 python tools/generate_calendar.py > paydaysuper/data/business_days.json
Then hand-review every line against the 8 state/territory government pages
before shipping, record the review date, and raise `verified_until` only to
the last date every jurisdiction covers. The raw generator deliberately
claims no coverage past regime commencement and marks every later date
provisional until confirmed.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import date

import holidays  # dev-only, pinned

JURISDICTIONS = ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"]
YEARS = [2026, 2027, 2028]
RAW_VERIFIED_UNTIL = date(2026, 7, 1)

# Entries in python-holidays' PUBLIC category that are NOT public holidays
# for the whole of their jurisdiction, so must not remove a business day.
# Match the jurisdiction too: the same holiday name can be whole-of-state in
# one place and locally substituted in another.
NOT_WHOLE_OF_JURISDICTION = {
    ("QLD", "The Royal Queensland Show"),  # Brisbane area only (Ekka)
    # Regional WA areas substitute another day, so the default celebration
    # date does not apply throughout WA.
    ("WA", "King's Birthday"),
    # Non-metro Victorian councils may arrange an alternate local holiday.
    ("VIC", "Melbourne Cup Day"),
}

OFFICIAL_SOURCES = {
    "definition": (
        "https://www.ato.gov.au/tax-and-super-professionals/"
        "for-superannuation-professionals/super-funds-newsroom/"
        "business-days-decoded-why-it-matters-for-your-fund"
    ),
    "ACT": (
        "https://www.act.gov.au/living-in-the-act/"
        "public-holidays-school-terms-and-daylight-saving"
    ),
    "NSW": "https://www.nsw.gov.au/about-nsw/public-holidays",
    "NT": "https://nt.gov.au/nt-public-holidays",
    "QLD": "https://www.qld.gov.au/recreation/travel/holidays/public",
    "SA": "https://safework.sa.gov.au/resources/public-holidays",
    "TAS": "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays",
    "VIC": (
        "https://business.vic.gov.au/business-information/public-holidays/"
        "victorian-public-holidays-2027"
    ),
    "WA": (
        "https://www.wa.gov.au/service/employment/workplace-arrangements/"
        "public-holidays-western-australia"
    ),
}


def main() -> None:
    merged: dict[date, dict] = {}
    for jur in JURISDICTIONS:
        cal = holidays.Australia(subdiv=jur, years=YEARS, categories=("public",))
        for d, name in sorted(cal.items()):
            name = name.strip()
            if (jur, name) in NOT_WHOLE_OF_JURISDICTION:
                print(f"SKIP (not whole-of-state): {d} {jur} {name}", file=sys.stderr)
                continue
            entry = merged.setdefault(d, {"date": d.isoformat(), "names": defaultdict(list)})
            entry["names"][name].append(jur)

    out = []
    for d in sorted(merged):
        names = merged[d]["names"]
        label = "; ".join(sorted(names))
        jurs = sorted({j for js in names.values() for j in js})
        # Generated dates are reference candidates, not primary-source
        # verification. Keep every date after the raw completeness boundary
        # provisional until a human checks the official jurisdiction pages.
        provisional = d > RAW_VERIFIED_UNTIL
        out.append(
            {
                "date": d.isoformat(),
                "name": label,
                "jurisdictions": jurs,
                "provisional": provisional,
            }
        )

    # Provenance comes from the environment that actually ran, not from
    # literals: a hardcoded pin already went stale once (0.101 survived the
    # bump to 0.102), and a hardcoded date would stamp every future
    # regeneration with a false generation date.
    doc = {
        "_comment": (
            "Non-business days under SGAA 1992 s 6(1): public holidays applying to "
            "the WHOLE of any State/ACT/NT. Weekends are computed, not listed. "
            f"Generated by tools/generate_calendar.py (holidays=={holidays.__version__}), "
            "and REQUIRES hand-checking against the official jurisdiction sources "
            "recorded in this file before shipping. Part-day holidays (SA/QLD/NT "
            "Christmas & New Year's Eve evenings), "
            "regional holidays, WA King's Birthday and Melbourne Cup Day are excluded "
            "because they do not apply throughout a jurisdiction. Unconfirmed dates "
            "are retained as provisional reference entries but do not extend deadlines."
        ),
        "verified_from": "2026-07-01",
        # Generation is not official verification. A reviewer raises this
        # horizon only after checking every jurisdiction and records that
        # review date below. This makes accidental raw output fail closed.
        "verified_until": RAW_VERIFIED_UNTIL.isoformat(),
        "generated": date.today().isoformat(),
        "official_sources": {"checked": None, **OFFICIAL_SOURCES},
        "non_business_days": out,
    }
    json.dump(doc, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
