"""Generate paydaysuper/data/business_days.json: the national non-business-day table.

DEV-TIME TOOL ONLY. The runtime never imports python-holidays: compliance
output must not change because a transitive dependency updated, and the raw
package output is wrong for SGAA s 6(1) anyway (it lists Brisbane-area
Royal Queensland Show as a QLD PUBLIC holiday).

Method (SGAA 1992 s 6(1) "business day"):
  a day is NOT a business day if it is Sat/Sun, or a public holiday for the
  WHOLE of any State, the ACT or the NT. So: union of PUBLIC-category
  holidays across the 8 listed jurisdictions, minus entries that are not
  whole-of-jurisdiction, weekends excluded (computed at runtime).

Usage:
    pip install holidays==0.101
    python tools/generate_calendar.py > paydaysuper/data/business_days.json
Then hand-review every line against the 8 state/territory government pages
before shipping. Dates for proclaimed-yearly holidays are marked
provisional until gazetted.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import date

import holidays  # dev-only, pinned

JURISDICTIONS = ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"]
YEARS = [2026, 2027, 2028]

# Entries in python-holidays' PUBLIC category that are NOT public holidays
# for the whole of their jurisdiction, so must not remove a business day.
NOT_WHOLE_OF_JURISDICTION = {
    "The Royal Queensland Show",  # Brisbane area only (Ekka)
}

# Holidays proclaimed (or fixture-dependent) each year: rule-derived future
# dates are provisional until the state gazettes them.
PROVISIONAL_RULES = [
    ("VIC", "Grand Final Day", 2026),   # depends on AFL fixture each year
    ("WA", "King's Birthday", 2027),    # proclaimed annually, usually late Sep
]


def main() -> None:
    merged: dict[date, dict] = {}
    for jur in JURISDICTIONS:
        cal = holidays.Australia(subdiv=jur, years=YEARS, categories=("public",))
        for d, name in sorted(cal.items()):
            name = name.strip()
            if name in NOT_WHOLE_OF_JURISDICTION:
                print(f"SKIP (not whole-of-state): {d} {jur} {name}", file=sys.stderr)
                continue
            entry = merged.setdefault(d, {"date": d.isoformat(), "names": defaultdict(list)})
            entry["names"][name].append(jur)

    out = []
    for d in sorted(merged):
        names = merged[d]["names"]
        label = "; ".join(sorted(names))
        jurs = sorted({j for js in names.values() for j in js})
        provisional = any(
            jur in jurs and key in label and d.year >= from_year
            for jur, key, from_year in PROVISIONAL_RULES
        )
        out.append(
            {
                "date": d.isoformat(),
                "name": label,
                "jurisdictions": jurs,
                "provisional": provisional,
            }
        )

    doc = {
        "_comment": (
            "Non-business days under SGAA 1992 s 6(1): public holidays applying to "
            "the WHOLE of any State/ACT/NT. Weekends are computed, not listed. "
            "Generated by tools/generate_calendar.py (holidays==0.101), then "
            "hand-reviewed. Part-day holidays (SA/QLD/NT Christmas & New Year's "
            "Eve evenings) are treated as business days; Melbourne Cup Day is "
            "included with a documented whole-of-Victoria caveat. Provisional "
            "dates are rule-derived, not yet gazetted."
        ),
        "verified_from": "2026-07-01",
        "verified_until": "2028-12-31",
        "generated": "2026-08-02",
        "non_business_days": out,
    }
    json.dump(doc, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
